[versions]
gson-ver = "2.11.0"
junit-bom-ver = "5.10.0"
gradle-checksum-ver = "1.4.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson-ver" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom-ver" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

[plugins]
checksum = { id = "org.gradle.crypto.checksum", version.ref = "gradle-checksum-ver" }
